### ISSUE TITLE
Snow placed on top of signs

### ISSUE THREAD

**Issue by JBYoshi** [Flibio/WinterWonderland#1]
When I jump while standing inside of a sign, snow is placed on top of the sign.
![2015-12-16_18 40 12](https://cloud.githubusercontent.com/assets/12983479/11860565/b63430e6-a43b-11e5-92e2-8aa53abbedb2.png)
Also occurs with wall signs.

**Comment by Flibio** [comment]
Thanks for reporting the issue! I'll take a look at that!
